# -*- coding: utf-8 -*-
"""lab7 task 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FyK2uq3O_H_rBL1yCCfdnXEJbPjh85cu
"""

def count_ways(n):
    if  n==1 or n==0:
        return 1

    dp = [0] * (n+1)
    dp[0] = 1
    dp[1] = 1

    for val in range(2, n+1):
        dp[val] = dp[val-1] + dp[val-2]

    return dp[n]

input = open('input3_4.txt' , 'r')
output = open('output3_4.txt' , 'w')
n = int(input.readline())


result = count_ways(n)
output.write(str(result))

input.close()
output.close()