# -*- coding: utf-8 -*-
"""task 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10q6gCnV0fDkxAsa4Zt3VSlg1kYowRSRS
"""

def union(a,b,arr,size):
    f1 = friendcircle(a,arr)
    f2 = friendcircle(b,arr)
    if f1!=f2:
        arr[f2] = f1
        size[f1]=size[f2]+size[f1]

    return size[f1]

def friendcircle(r,arr):

    if r!=arr[r]:
        arr[r] = friendcircle(arr[r],arr)
        return arr[r]
    else:
        return r

input = open('input1_1.txt' , 'r')
output = open('output1_1.txt' , 'w')
val = input.readline().split(' ')
n=val[0]
k=val[1]
n, k = int(n), int(k)
arr = [0]*(n+1)
size = [1]*(n+1)
for i in range(n+1):
    arr[i] = i

for j in range(k):
    a, b = input.readline().strip().split(" ")
    a, b = int(a),int(b)
    res = union(a,b,arr,size)
    print(res, file = output)