# -*- coding: utf-8 -*-
"""Task 6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T9_TwY5QK2_xDlfvg3SrcW6LnKdVpDDu
"""

input = open('input6.txt', 'r')
output = open('output6.txt', 'w')

def quickselect(arr, k):
    if len(arr) == 1:
        return arr[0]
    small=[]
    big=[]
    equal=[]
    pivot = arr[len(arr) // 2]

    for val in arr:
      if val>pivot:
        big.append(val)
      elif val<pivot:
        small.append(val)
      else:
        equal.append(val)

    if k < len(small):
        return quickselect(small, k)
    elif k < len(small) + len(equal):
        return equal[0]
    else:
        return quickselect(big, k - len(small) - len(equal))


N=int(input.readline())
arr=list(map(int, input.readline().split()))
Q=int(input.readline())
queries=[]
for q in range(Q):
  queries.append(int(input.readline()))
for k in queries:
  print(quickselect(arr, k - 1),file=output)


input.close()
output.close()