# -*- coding: utf-8 -*-
"""Task 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12w2YXcZmKX9TF4U97IxHJGRXk8okC3ka
"""

input=open("input4.txt","r")
output=open("output4.txt","w")
length=int(input.readline())
def maximum(arr ,length):
    max1 = 1
    max2 = 0
    result=0
    for i in range(1 ,length):
        if (arr[i])**2>=arr[max1]**2 :
            max1 = i

    for j in range(0 , max1):
        if arr[max2]<arr[j]:
            max2 = j

    result = arr[max2] + arr[max1]**2
    return result

while True:
   try:
        a1 = list(map(int, input.readline().strip().split(" ")))
        comparing = maximum(a1 , int(length))
        print(comparing, file = output)
   except:
       break
input.close()
output.close()