# -*- coding: utf-8 -*-
"""Task 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VaMP0UN8h88EhagZufV0XDkNW1pxQdCg

TASK 01
"""

input=open("input1.txt","r")
output=open("output1.txt","w")

num=input.readline().split()
list1=input.readline().split()


def merge(a,b):
    merged=[]
    i = j = 0
    while i < len(a) and j < len(b):
        if int(a[i]) <= int(b[j]):
            merged.append(a[i])
            i += 1
        else:
            merged.append(b[j])
            j += 1
    while i < len(a):
        merged.append(a[i])
        i += 1
    while j < len(b):
        merged.append(b[j])
        j += 1
    return merged

def mergeSort(arr):
    if len(arr) <= 1:
        return arr
    else:
        mid = len(arr)//2
        a1 = mergeSort(arr[:mid])
        a2 = mergeSort(arr[mid:])
        return merge(a1, a2)


final=mergeSort(list1)


for j in final:
  output.write(j)
  output.write(" ")

input.close()
output.close()