# -*- coding: utf-8 -*-
"""Task 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lfBi6Qxai1aOWUuewjufDmRjmiwEYHcA

Task 03
"""

input = open("input3.txt", "r")
output = open("output3.txt", "w")
num_alien = int(input.readline())
def count(arr):
    l=0
    r=0
    count1=0
    if len(arr) <= 1:
        return 0
    mid = len(arr) // 2
    left = arr[:mid]
    right = arr[mid:]
    total =count(left) + count(right)

    while l<len(left) and r<len(right):
        if left[l] < right[r]:
           l+=1
        else:
            count1 += len(left) - l
            r += 1
    arr[:] = sorted(arr)
    return total + count1

while True:
   try:
        height_alien = list(map(int, input.readline().split()))
        ans =count(height_alien)
        print(ans,file=output)
        n = int(input.readline())

   except:
        break
input.close()
output.close()