# -*- coding: utf-8 -*-
"""Task 5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TiCPsSn8p2f1kYipqv8P9KznYlkNbAYz
"""

input = open('input5.txt', 'r')
output = open('output5.txt', 'w')
n = int(input.readline())

def quick_Sort(arr, low, high):
	if low < high:
		pivot = partition(arr, low, high)
		quick_Sort(arr, low, pivot - 1)
		quick_Sort(arr, pivot + 1, high)

def partition(arr, low, high):
	pivot = arr[high]
	i = low - 1
	for j in range(low, high):
		if arr[j] <= pivot:
			i = i + 1
			(arr[i], arr[j]) = (arr[j], arr[i])
	(arr[i + 1], arr[high]) = (arr[high], arr[i + 1])
	return i + 1





while True:
    try:
        array1 = list(map(int, input.readline().strip().split(" ")))
        a = quick_Sort(array1, 0, int(n) - 1)
        print(*array1, file = output)
        n = input.readline().strip()
    except:
        break
input.close()
output.close()