# -*- coding: utf-8 -*-
"""Task 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12G9XDkJhK9oWsbBmv2Qkh4GqzyYBIs0k
"""

input=open("input2.txt","r")
output=open("output2.txt","w")
def divide (arr):
  if len(arr)<=1:
    return arr
  else:
    mid=len(arr)//2
    arr1=divide(arr[:mid])
    arr2=divide(arr[mid:])
    if arr1!=None and arr2!=None:
     maximum=max(arr1,arr2)
     return maximum

num=input.readline().split()
alice=list(map(int,input.readline().split()))
ans=divide(alice)
output.write(str(ans[-1]))

input.close()
output.close()