# -*- coding: utf-8 -*-
"""task6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cPFtSYJyPFKN-fGhTTGIicFzGg4rcOMI
"""

input = open('input6_3.txt', 'r')
output = open('output6_3.txt', 'w')
r,h=input.readline().split()


def travel(i, j):
  if list1[i][j]=='D':
    if [i, j] not in list2:
       list2.append([i, j])

  go=[[i+1, j], [i-1, j], [i, j+1], [i, j-1]]

  for val in go:
    if new[val[0]][val[-1]]==0: # checks if unvisited
      new[i][j]="T"
      travel(val[0], val[1])



lines = input.read().split()
list1 = []
list1.append(['#']*(int(h)+2))
for l in range(len(lines)):
  eachline=[]
  eachline.append("#")
  for letter in lines[l]:
    eachline.append(letter)
  eachline.append("#")
  list1.append(eachline)
list1.append(["#"]*(int(h)+2))
print(eachline)
print(list1)


new= []
for i in range(int(r)+2):
  line=[]
  for j in range(int(h)+2):
    if list1[i][j]=='#':
      line.append("T")
    else:
      line.append(0)
  new.append(line)
print(new)


maxcount = 0
for i in range(int(r)+2):
  for j in range(int(h)+2):
    if  list1[i][j]=='.':
     if new[i][j]==0:
      list2=[]
      call=travel(i, j)
      maxcount =max(len(list2),maxcount)

output.write(str(maxcount))
input.close()
output.close()

