# -*- coding: utf-8 -*-
"""Task 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DndNXqoLH3iG3ShR1LOenvs9gNO0a7fd

TASK 3
"""

with open("input3.txt","r") as file :
   student=file.read()

with open("input3.txt","r") as file :
  value=file.readlines()
  id=value[1].split()
  mark=value[2].split()

  dic={}
  for i in range(len(id)):
    dic[id[i]]=mark[i]

  for i in range(len(id)):
    min1=i
    min2=i
    for j in range(i,len(id) ):
      if int(id[j])<int(id[min2]):
        min2=j
      if int(mark[j])<int(mark[min1]):
        min1=j
    mark[i],mark[min1]=mark[min1],mark[i]
    id[i],id[min2]=id[min2],id[i]

  with open("output3.txt","a") as file :
    for i in range(len(mark)-1,-1,-1):
      for val in range(len(id)):
        if id[val]!="0":
         if dic[id[val]]==mark[i]:
          file.write(" ID: ")
          file.write(id[val])
          file.write(" Mark: ")
          file.write(mark[i])
          file.write("\n")
          id[val]="0"