# -*- coding: utf-8 -*-
"""Task 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DdIjRCwwR9KzRghIcFcmpp8jCm4zS06T

TASK 02
"""

with open("input2.txt","r") as file :
   value=file.read()

with open("input2.txt","r") as file :
  value=file.readlines()
  arr=value[1].split()
  with open("output2.txt","a") as file :
       swapping=False
       for i in range(len(arr)-1):
         for j in range(len(arr)-i-1):
            if int(arr[j]) > int(arr[j+1]):
                arr[j], arr[j+1] = arr[j+1], arr[j]
                swapping=True
         if swapping==False and i==0:

           for val in arr:
              file.write(" "+val+" ")
         if i==len(arr)-2 and swapping==True:
          for val in arr:
           file.write(" "+val+" ")

"""EXPLANATION:
This code will run for theta(n) as for the best scenerio, the outer loop won't have to traverse n number of times, rather in the first traversing (i.e, i=0) due to not facing any swapping- it would generate its output sequentially.
"""