# -*- coding: utf-8 -*-
"""Task 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VjQ-4vDqpMe0l-sP9hPZ87rBK521Nq8j

TASK 4
"""

with open("input4.txt","r") as file:
  train=file.read()

with open("input4.txt","r") as file:
  name=file.readlines()
  nametime=[]
  new=[]
  for val in name[1::] :
    perline=val.split()
    new.append(val)
    nametime.append([perline[0],perline[-3],perline[-1]])
  with open("output4.txt","a") as file :
        for i in range(len(nametime)-1):
          for j in range(len(nametime)-i-1):
             if ord(nametime[j][0][0])>ord(nametime[j+1][0][0]):
                nametime[j], nametime[j+1] = nametime[j+1], nametime[j]
             else:
               if ord(nametime[j][0][0])==ord(nametime[j+1][0][0]):
                if len(nametime[j][0])>len(nametime[j+1][0]) :
                 nametime[j], nametime[j+1] = nametime[j+1], nametime[j]
                else:
                 if len(nametime[j][0])==len(nametime[j+1][0]) :
                  if nametime[j][0][-1]==nametime[j+1][0][-1]:
                    if int(nametime[j][2][0]+nametime[j][2][1])<int(nametime[j+1][2][0]+nametime[j+1][2][1]):
                      nametime[j], nametime[j+1] = nametime[j+1], nametime[j]
                  else:
                   if int(nametime[j][2][0]+nametime[j][2][1])>int(nametime[j+1][2][0]+nametime[j+1][2][1]):
                      nametime[j], nametime[j+1] = nametime[j+1], nametime[j]


        for i in range(len(nametime)):
          for j in range(len(new)):
            if (nametime[i][0] in new[j]) and (nametime[i][1] in new[j]) and (nametime[i][2] in new[j]):
              file.write (new[j])