# -*- coding: utf-8 -*-
"""Task 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16OdykWExg10od7r9jEQOGW6xKDJAyNdb

TASK 01 (a)
"""

with open("input1a.txt","r") as file : # file er bodole onno kichu lekha jabe # r FOR READING
  content=file.read()

with open("input1a.txt","r") as file :
  value=file.readlines()
  for i in value[1::] :
    n=int(i)
    with open("output1a.txt","a") as file : # a mane append, onekgular line er jonno output show korte thake # w executes for one line

      if n%2==0:
        file.write( str(n))
        file.write(" is an Even number. \n")
      else:
        file.write(str(n))
        file.write(" is an Odd number. \n")

"""TASK 01 (b)"""

with open("input1b.txt","r") as file :
  prob=file.read()

with open("input1b.txt","r") as file:
   calc=file.readlines()
   for i in range(1,len(calc)):
     var=calc[i].split()
     print(var)
     in1=var[1]
     sign=var[2]
     in2=var[3]
     with open("output1b.txt","a") as file :
       if sign=="+":
         ans=int(in1)+int(in2)
       if sign=="-":
         ans=int(in1)-int(in2)
       if sign=="*":
         ans=int(in1)*int(in2)
       if sign=="/":
         ans=int(in1)/int(in2)

       file.write("\n The result of ")
       file.write(in1+" "+sign+" "+in2)
       file.write(" is ")
       file.write(str(ans))