# -*- coding: utf-8 -*-
"""task4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fNP2-EpwX1UugFbRMXhqUGem3mdKWpF1
"""

with open("input4.txt","r") as file :
  content=file.read()

with open("input4.txt","r") as file :
  value=file.readline()
  list1=[]
  per=int(value[2])
  for i in range(int(value[0])):
    list1.append(file.readline().split())

def mergesort(arr):
    if len(arr) <= 1:
        return arr
    mid = len(arr) // 2
    left = arr[:mid]
    right = arr[mid:]
    left = mergesort(left)
    right = mergesort(right)
    return merge(left, right)
def merge(left,right):
    merged=[]
    i = j = 0
    while i < len(left) and j < len(right):
        if int(left[i][1]) <= int(right[j][1]):
            merged.append(left[i])
            i += 1
        else:
            merged.append(right[j])
            j += 1
    while i < len(left):
        merged.append(left[i])
        i += 1
    while j < len(right):
        merged.append(right[j])
        j += 1
    return merged

final=mergesort(list1)


per1=[]
per2=[]
per3=[]

count=0

for val in range(len(final)):
 if per==2:
   if val==0:
     per1.append(final[val])
     count+=1
     final[val]=None
   elif len(per2)==0 and val!=0 :
     if per1[-1][-1]!=final[val][0]:
       per2.append(final[val])
       count+=1
       final[val]=None
       break

 if per==3:
  if val==0:
     per1.append(final[val])
     count+=1
     final[val]=None
  elif len(per2)==0 and val!=0 :
     if per1[-1][-1]!=final[val][0]:
       per2.append(final[val])
       count+=1
       final[val]=None
  elif len(per2)==len(per1):
    if per2[-1][-1]!=final[val][0] and per1[-1][-1]!=final[val][0]:
      per3.append(final[val])
      count+=1
      final[val]=None
      break

for val in range(len(final)):
  if final[val]!=None and per==2:
    if per1[-1][-1]==final[val][0] and len(per1)==len(per2):
      per1.append(final[val])
      count+=1
      final[val]=None
    elif per2[-1][-1]==final[val][0] and len(per1)==len(per2):
      per2.append(final[val])
      count+=1
      final[val]=None
    elif per2[-1][-1]<final[val][0] and len(per1)==len(per2):
      per2.append(final[val])
      count+=1
      final[val]=None
    elif per1[-1][-1]<final[val][0] and len(per1)==len(per2):
      per1.append(final[val])
      count+=1
      final[val]=None

    elif len(per2)==len(per1)-1:
      if per1[-1][-1]!=final[val][0] and per2[-1][-1]<=final[val][0]:
        per2.append(final[val])
        count+=1
        final[val]=None
    elif len(per1)==len(per2)-1:
      if per2[-1][-1]!=final[val][0] and per1[-1][-1]<=final[val][0]:
        per1.append(final[val])
        count+=1
    else:
      final[val]=None


  if final[val]!=None and per==3:
    if per1[-1][-1]==final[val][0] and len(per1)==len(per2)==len(per3):
      per1.append(final[val])
      count+=1
      final[val]=None
    elif per2[-1][-1]==final[val][0] and len(per1)==len(per2)==len(per3):
      per2.append(final[val])
      count+=1
      final[val]=None
    elif per3[-1][-1]==final[val][0] and len(per1)==len(per2)==len(per3):
      per3.append(final[val])
      count+=1
      final[val]=None
    elif per1[-1][-1]<final[val][0] and len(per1)==len(per2)==len(per3):
      per1.append(final[val])
      count+=1
      final[val]=None
    elif per2[-1][-1]<final[val][0] and len(per1)==len(per2)==len(per3):
      per2.append(final[val])
      count+=1
      final[val]=None
    elif per3[-1][-1]<final[val][0] and len(per1)==len(per2)==len(per3):
      per3.append(final[val])
      count+=1
      final[val]=None
    elif per2[-1][-1]!=final[val][0] and per3[-1][-1]!=final[val][0] and per1[-1][-1]<=final[val][0]:
        if int(final[val][0])-int(per3[-1][-1])<int(final[val][0])-int(per1[-1][-1]):
          per3.append(final[val])
          count+=1
          final[val]=None
        elif int(final[val][0])-int(per2[-1][-1])<int(final[val][0])-int(per1[-1][-1]):
          per2.append(final[val])
          count+=1
          final[val]=None

        else:
         per1.append(final[val])
         count+=1
         final[val]=None
    elif per1[-1][-1]!=final[val][0] and per3[-1][-1]!=final[val][0] and per2[-1][-1]<=final[val][0]:
        if int(final[val][0])-int(per3[-1][-1])<int(final[val][0])-int(per2[-1][-1]):
          per3.append(final[val])
          count+=1
          final[val]=None
        elif int(final[val][0])-int(per1[-1][-1])<int(final[val][0])-int(per2[-1][-1]):
          per1.append(final[val])
          count+=1
          final[val]=None

        else:
          per2.append(final[val])
          count+=1
          final[val]=None
    elif per2[-1][-1]!=final[val][0] and per1[-1][-1]!=final[val][0] and per3[-1][-1]<=final[val][0]:
        if int(final[val][0])-int(per2[-1][-1])<int(final[val][0])-int(per3[-1][-1]):
          per2.append(final[val])
          count+=1
          final[val]=None
        elif int(final[val][0])-int(per1[-1][-1])<int(final[val][0])-int(per3[-1][-1]):
          per1.append(final[val])
          count+=1
          final[val]=None


        else:
          per3.append(final[val])
          count+=1
          final[val]=None
    else:
      final[val]=None
with open("output4.txt","w") as file:
  file.write(str(count))