# -*- coding: utf-8 -*-
"""task2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15XIaGZO3Gq5gS3l4Aj_zNyhAhSqV6Ml2
"""

#lab task2 part1
input=open("input2a.txt","r")
output=open("output2a.txt","w")


ab=[]
alice=input.readline().split()
alice1=input.readline().split()
lena=len(alice1)

bob=input.readline().split()
bob1=input.readline().split()
lenb=len(bob1)

for a in alice1:
   ab.append(a)
for b in bob1:
  ab.append(b)


def mergesort(arr):
    if len(arr) <= 1:
        return arr
    mid = len(arr) // 2
    left = arr[:mid]
    right = arr[mid:]
    left = mergesort(left)
    right = mergesort(right)
    return merge(left, right)
def merge(left,right):
    merged=[]
    i = j = 0
    while i < len(left) and j < len(right):
        if int(left[i]) <= int(right[j]):
            merged.append(left[i])
            i += 1
        else:
            merged.append(right[j])
            j += 1
    while i < len(left):
        merged.append(left[i])
        i += 1
    while j < len(right):
        merged.append(right[j])
        j += 1
    return merged

final=mergesort(ab)

for j in final:
  output.write(j)
  output.write(" ")
input.close()
output.close()

#lab task2 part2
input=open("input2b.txt","r")
output=open("output2b.txt","w")
alice=input.readline().split()
alice1=input.readline().split()
lena=len(alice1)

bob=input.readline().split()
bob1=input.readline().split()
lenb=len(bob1)


lp1=0
lp2=0
combined=[]
n=lena+lenb

for i in range(n):
 if lp1<lena and lp2<lenb:
   if int(alice1[lp1])<int(bob1[lp2]):
     combined.append(alice1[lp1])
     lp1+=1
   elif int(bob1[lp2])<int(alice1[lp1]):
     combined.append(bob1[lp2])
     lp2+=1
   else:
    combined.append(bob1[lp2])
    combined.append(alice1[lp1])
    lp1+=1
    lp2+=1

if lp1>=lena and lp2<lenb:
  for val in range(lp2,lenb):
      combined.append(bob1[val])
if lp2>=lenb and lp1<lena:
  for var in range(lp1,lena):
      combined.append(alice1[var])

for val in combined:
  output.write(str(val))
  output.write(str(" "))
input.close()
output.close()